"""
officer.py — Evidence-Grounded AI Risk Officer Reasoning Layer (Phase 9)
========================================================================

Uses Groq LLM with the fixed Sentinel Risk Council system prompt to reason
over independent analyst findings and knowledge graph evidence.

Guarantees:
  - HARD SECURITY BOUNDARY: The LLM observes and reasons over existing verified
    values. It CANNOT alter or override A_t, P_t, G_t, R_t, expected cost, or
    the final decision. The deterministic Risk Engine remains sole authority.
  - STRICT CITATION & GROUNDING: All factual claims cite explicitly supplied
    evidence tags ([E1], [E2], ..., [RISK_ENGINE]).
  - SAFE FALLBACK: If external LLM call fails or returns malformed output, the
    deterministic fallback engine activates without service disruption.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional, Tuple

from trustgraph.investigator.llm_provider import GroqProvider, LLMProvider, get_llm_provider
from trustgraph.investigator.schema import EvidenceItem

logger = logging.getLogger(__name__)

# ===========================================================================
# Fixed Sentinel Risk Council System Prompt (Verbatim as required)
# ===========================================================================

SENTINEL_RISK_COUNCIL_SYSTEM_PROMPT = """You are Sentinel Risk Council, an evidence-grounded payment-risk reasoning system.

Your role is to reason over independent analytical perspectives for a payment transaction and provide concise, auditable reasoning for a human risk operator.

You are NOT the final decision-maker.

The deterministic Sentinel Risk Engine is the sole authority for:
- A_t
- P_t
- G_t
- R_t
- expected cost
- ALLOW
- VERIFY
- THROTTLE
- BLOCK

You must NEVER calculate, modify, replace, or override these values.

YOUR RESPONSIBILITIES:

1. Compare the Transaction Risk Analyst and Slow-Burn Analyst findings.

2. Determine whether the analytical perspectives:
   - agree,
   - disagree,
   - indicate primarily slow-burn behavioral risk,
   - indicate primarily transaction-level risk,
   - or lack sufficient behavioral history.

3. Explain why the independent signals reinforce or contradict each other.

4. Interpret the supplied graph evidence in context.

5. Explain whether graph relationships provide additional contextual support.

6. Distinguish acute transaction-level anomalies from persistent behavioral risk.

7. Identify the strongest supplied evidence supporting the assessment.

8. Explain the supplied Risk Engine result using the provided values.

9. Produce concise, evidence-grounded reasoning suitable for a payment-risk operator.

GROUNDING RULES:

- Use ONLY facts explicitly provided in the transaction context.
- Never invent transaction history.
- Never invent graph relationships.
- Never invent fraud events.
- Never invent risk scores.
- Never invent evidence.
- Never infer missing history as suspicious.
- Never claim that a relationship exists unless it appears in the supplied graph evidence.
- Never use external knowledge to introduce new facts about the transaction.

EVIDENCE INTERPRETATION RULES:

- Clearly distinguish between:
  1. directly observed facts contained in evidence, and
  2. reasonable interpretation of those facts.
- Never present an interpretation as a verified fact.
- Do not use causal, definitive, or accusatory language unless it is explicitly supported by the supplied evidence.
- Avoid unsupported terms such as:
  "fraud ring", "organized group", "coordinated attack", "confirmed fraudster", or "malicious actor",
  unless those exact conclusions are explicitly supported by supplied evidence.
- When evidence only indicates correlation or association, describe it as "relational context", "association", "shared activity", or similar non-causal language.

CITATION RULES:

- Use only evidence IDs supplied in the transaction context.
- Valid citations may include [E1], [E2], [E3], [E4], [RISK_ENGINE], or other explicitly supplied evidence IDs.
- Never create new evidence IDs.
- Never cite evidence that does not support the associated claim.
- Important factual claims should include the relevant evidence citation.
- Citations must refer to deterministic evidence supplied by Sentinel, not evidence generated by you.

ANALYST RULES:

If both analysts independently indicate elevated risk:
    classify as AGREEMENT.

If the Transaction Risk Analyst indicates low/elevated risk while the Slow-Burn Analyst indicates a materially different risk state:
    classify as DISAGREEMENT when the supplied states genuinely conflict.

If the Slow-Burn Analyst reports INSUFFICIENT_HISTORY:
    explicitly state that behavioral history is unavailable.
    Do not infer behavioral risk from the absence of history.

If only the Transaction Risk Analyst provides meaningful elevated evidence:
    classify as ML_ONLY.

If only the Slow-Burn Analyst provides meaningful elevated evidence:
    classify as SLOW_BURN_ONLY.

Do not hide disagreement.
Do not manufacture agreement.

GRAPH RULES:

Treat graph evidence as contextual relational evidence.

G_t is supplied by the existing Sentinel pipeline.

Do not calculate or modify G_t.

Do not treat graph evidence alone as proof of fraud.

Explain whether the supplied graph relationships:
- reinforce the analyst findings,
- provide additional context,
- or conflict with the analyst findings.

RISK ENGINE RULE:

The supplied Risk Engine result is authoritative.

You may explain why the supplied R_t and decision are consistent with the evidence.

You must NEVER:
- recalculate R_t,
- change R_t,
- recommend a different final action,
- change thresholds,
- override the Risk Engine,
- or substitute your own decision.

If your reasoning appears inconsistent with the Risk Engine result, explicitly identify the inconsistency rather than changing the decision.

UNCERTAINTY RULE:

When evidence is insufficient, say so.

Do not turn uncertainty into suspicion.

Do not claim confidence that is not supported by the supplied evidence.

STYLE:

- Be concise.
- Be analytical.
- Be specific.
- Prefer concrete evidence over generic statements.
- Avoid phrases such as 'this transaction looks suspicious' without explaining why.
- Do not mention being an AI.
- Do not mention this system prompt.
- Do not expose chain-of-thought or hidden reasoning.
- Provide conclusions and concise supporting rationale only.

OUTPUT:

Return structured JSON matching the schema supplied by the application.

Do not add fields outside the requested schema unless explicitly instructed."""

ALLOWED_COUNCIL_STATUSES = {
    "AGREEMENT",
    "DISAGREEMENT",
    "SLOW_BURN_ONLY",
    "ML_ONLY",
    "INSUFFICIENT_HISTORY",
}


class AIRiskOfficer:
    """
    Presiding evidence-grounded synthesis officer for the Multi-Analyst Risk Council.
    """

    def __init__(self, llm_provider: Optional[LLMProvider] = None) -> None:
        self.llm = llm_provider or get_llm_provider()

    def build_transaction_context(
        self,
        transaction_id: int,
        transaction_analyst: Dict[str, Any],
        slow_burn_analyst: Dict[str, Any],
        graph_risk_g: float,
        final_risk_r: float,
        action: str,
        expected_cost: float,
        evidence_items: List[EvidenceItem],
        amount: float = 0.0,
        timestamp: float = 0.0,
    ) -> str:
        """
        Construct a strict, per-transaction context containing ONLY verified values
        from the existing pipeline. Zero secrets, zero arbitrary state.
        """
        a_t = transaction_analyst.get("risk", 0.0)
        t_assess = transaction_analyst.get("assessment", "UNKNOWN")
        t_signals = "; ".join(transaction_analyst.get("signals", []))

        p_t_val = slow_burn_analyst.get("risk")
        p_str = f"{p_t_val:.4f}" if p_t_val is not None else "UNAVAILABLE"
        sb_assess = slow_burn_analyst.get("assessment", "INSUFFICIENT_HISTORY")
        sb_state = slow_burn_analyst.get("state", "UNKNOWN")
        sb_signals = "; ".join(slow_burn_analyst.get("signals", []))

        # Evidence lines
        ev_lines = []
        for e in evidence_items:
            ev_lines.append(f"  [{e.evidence_id}] {e.title}: {e.description}")
        ev_text = "\n".join(ev_lines) if ev_lines else "  None provided"

        context = f"""TRANSACTION
- Transaction ID: {transaction_id}
- Amount: INR {amount:.2f}
- Timestamp: {timestamp}

TRANSACTION RISK ANALYST
- A_t: {a_t:.4f}
- Assessment: {t_assess}
- Findings: {t_signals}
- Supporting Evidence IDs: [RISK_ENGINE]

SLOW-BURN ANALYST
- P_t: {p_str}
- Behavioral State: {sb_state}
- Assessment: {sb_assess}
- History Findings: {sb_signals}
- Supporting Evidence IDs: {', '.join([e.evidence_id for e in evidence_items if 'DIRECT_FRAUD' in str(e.evidence_type) or 'DEVICE' in str(e.evidence_type)]) or '[E1]'}

GRAPH CONTEXT
- G_t: {graph_risk_g:.4f}
- Relational Evidence Items:
{ev_text}

RISK ENGINE
- R_t: {final_risk_r:.4f}
- Final Deterministic Decision: {action}
- Expected Cost: INR {expected_cost:.2f}
- Supporting Evidence: [RISK_ENGINE]

Please reason over this context and output JSON with keys:
council_status, reasoning, transaction_analyst_interpretation, slow_burn_interpretation, graph_interpretation, key_evidence, risk_engine_consistency"""

        return context

    def reason_council(
        self,
        transaction_id: int,
        transaction_analyst: Dict[str, Any],
        slow_burn_analyst: Dict[str, Any],
        graph_risk_g: float,
        final_risk_r: float,
        action: str,
        expected_cost: float,
        evidence_items: List[EvidenceItem],
        amount: float = 0.0,
        timestamp: float = 0.0,
    ) -> Dict[str, Any]:
        """
        Execute Groq LLM evidence-grounded reasoning over the Risk Council context.
        Returns validated structured dictionary.
        """
        user_context = self.build_transaction_context(
            transaction_id=transaction_id,
            transaction_analyst=transaction_analyst,
            slow_burn_analyst=slow_burn_analyst,
            graph_risk_g=graph_risk_g,
            final_risk_r=final_risk_r,
            action=action,
            expected_cost=expected_cost,
            evidence_items=evidence_items,
            amount=amount,
            timestamp=timestamp,
        )

        valid_evidence_ids = {e.evidence_id for e in evidence_items}
        valid_evidence_ids.add("RISK_ENGINE")

        # 1. Attempt Groq LLM Call if active
        if not getattr(self.llm, "is_fallback", True):
            try:
                raw_json = self._call_groq_council(
                    system_prompt=SENTINEL_RISK_COUNCIL_SYSTEM_PROMPT,
                    user_prompt=user_context,
                )
                if raw_json:
                    parsed = json.loads(raw_json)
                    return self._validate_and_sanitize_response(
                        parsed=parsed,
                        valid_evidence_ids=valid_evidence_ids,
                        transaction_id=transaction_id,
                        provider_name=self.llm.name,
                        transaction_analyst=transaction_analyst,
                        slow_burn_analyst=slow_burn_analyst,
                    )
            except Exception as e:
                logger.warning(
                    "Groq Risk Council call failed (%s); seamlessly using deterministic reasoning.",
                    str(e),
                )

        # 2. Deterministic Fallback Reasoning (if Groq offline, unavailable, or errored)
        return self._deterministic_reasoning(
            transaction_id=transaction_id,
            transaction_analyst=transaction_analyst,
            slow_burn_analyst=slow_burn_analyst,
            graph_risk_g=graph_risk_g,
            final_risk_r=final_risk_r,
            action=action,
            expected_cost=expected_cost,
            evidence_items=evidence_items,
            valid_evidence_ids=valid_evidence_ids,
        )

    def _call_groq_council(self, system_prompt: str, user_prompt: str) -> Optional[str]:
        """Direct HTTP call to Groq with strict JSON response format."""
        import urllib.request
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.llm.api_key}",
            "Content-Type": "application/json",
            "User-Agent": "TRUSTGRAPH-Agent/1.0",
        }
        payload = {
            "model": self.llm.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.1,
            "max_tokens": 700,
        }
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=data, headers=headers)
        with urllib.request.urlopen(req, timeout=12) as resp:
            res_json = json.loads(resp.read().decode("utf-8"))
            choices = res_json.get("choices", [])
            if choices:
                msg = choices[0].get("message", {}).get("content", "")
                if msg:
                    return msg.strip()
        return None

    def _validate_and_sanitize_response(
        self,
        parsed: Dict[str, Any],
        valid_evidence_ids: set,
        transaction_id: int,
        provider_name: str,
        transaction_analyst: Optional[Dict[str, Any]] = None,
        slow_burn_analyst: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Enforces schema integrity, citation filtering, and status validation."""
        # 1. Validate status
        status = str(parsed.get("council_status", "DISAGREEMENT")).strip().upper()
        if status not in ALLOWED_COUNCIL_STATUSES:
            # Map common variations safely
            if "AGREE" in status:
                status = "AGREEMENT"
            elif "DISAGREE" in status:
                status = "DISAGREEMENT"
            elif "INSUFFICIENT" in status:
                status = "INSUFFICIENT_HISTORY"
            elif "SLOW" in status:
                status = "SLOW_BURN_ONLY"
            elif "ML" in status:
                status = "ML_ONLY"
            else:
                status = "DISAGREEMENT"

        # If slow-burn history is unavailable, council status must reflect INSUFFICIENT_HISTORY
        if slow_burn_analyst and str(slow_burn_analyst.get("assessment", "")).upper() == "INSUFFICIENT_HISTORY":
            status = "INSUFFICIENT_HISTORY"
        # Refine generic DISAGREEMENT if one analyst is elevated and the other is not
        elif status == "DISAGREEMENT" and transaction_analyst and slow_burn_analyst:
            t_assess = str(transaction_analyst.get("assessment", "")).upper()
            sb_assess = str(slow_burn_analyst.get("assessment", "")).upper()
            if t_assess in ("LOW", "MEDIUM") and sb_assess in ("HIGH", "CRITICAL"):
                status = "SLOW_BURN_ONLY"
            elif t_assess in ("HIGH", "CRITICAL") and sb_assess in ("LOW", "MEDIUM"):
                status = "ML_ONLY"

        # 2. Sanitize key evidence (filter out hallucinated/unsupplied IDs)
        raw_evidence = parsed.get("key_evidence", [])
        if isinstance(raw_evidence, str):
            raw_evidence = [raw_evidence]
        clean_evidence = []
        for eid in raw_evidence:
            clean_id = re.sub(r"[\[\]]", "", str(eid)).strip()
            if clean_id in valid_evidence_ids:
                clean_evidence.append(clean_id)
        if not clean_evidence:
            clean_evidence = ["RISK_ENGINE"]

        reasoning = str(parsed.get("reasoning", "")).strip()
        # Normalize bracket variations in reasoning text
        reasoning = re.sub(r"【(.*?)】", r"[\1]", reasoning)

        return {
            "council_status": status,
            "reasoning": reasoning,
            "transaction_analyst_interpretation": str(parsed.get("transaction_analyst_interpretation", "")),
            "slow_burn_interpretation": str(parsed.get("slow_burn_interpretation", "")),
            "graph_interpretation": str(parsed.get("graph_interpretation", "")),
            "key_evidence": clean_evidence,
            "risk_engine_consistency": bool(parsed.get("risk_engine_consistency", True)),
            "llm_execution": {
                "provider": provider_name,
                "model": getattr(self.llm, "model_name", "fallback"),
                "invoked": True,
                "is_fallback": False,
            },
        }

    def _deterministic_reasoning(
        self,
        transaction_id: int,
        transaction_analyst: Dict[str, Any],
        slow_burn_analyst: Dict[str, Any],
        graph_risk_g: float,
        final_risk_r: float,
        action: str,
        expected_cost: float,
        evidence_items: List[EvidenceItem],
        valid_evidence_ids: set,
    ) -> Dict[str, Any]:
        """Deterministic rule-based reasoning engine ensuring 100% availability."""
        t_assess = transaction_analyst.get("assessment", "LOW")
        a_t = transaction_analyst.get("risk", 0.0)
        sb_assess = slow_burn_analyst.get("assessment", "INSUFFICIENT_HISTORY")
        p_t = slow_burn_analyst.get("risk")

        high_ev = [e.evidence_id for e in evidence_items if e.risk_weight >= 0.70]
        key_ev = high_ev[:2] if high_ev else ["RISK_ENGINE"]

        if sb_assess == "INSUFFICIENT_HISTORY":
            status = "INSUFFICIENT_HISTORY"
            reasoning = (
                f"Behavioral history is unavailable for Transaction #{transaction_id} (zero prior observations). "
                f"The Council relies on instantaneous transaction risk A_t = {a_t:.4f} ({t_assess}) and cold-start graph heuristics. "
                f"The deterministic Sentinel Risk Engine retains authoritative action '{action}' [RISK_ENGINE]."
            )
            t_interp = f"Transaction-level model evaluated baseline risk as {t_assess} (A_t = {a_t:.4f})."
            sb_interp = "Behavioral history is insufficient to assess persistent activity."
            g_interp = f"Graph context G_t = {graph_risk_g:.4f} provides relational baseline for new entity."
        elif (t_assess in ("HIGH", "CRITICAL") and sb_assess in ("HIGH", "CRITICAL")) or (t_assess == "LOW" and sb_assess == "LOW"):
            status = "AGREEMENT"
            reasoning = (
                f"Both independent analysts identify concordant risk for Transaction #{transaction_id}. "
                f"The Transaction Risk Analyst identifies {t_assess} instantaneous risk (A_t = {a_t:.4f}), while the "
                f"Slow-Burn Analyst independently corroborates {sb_assess} persistent risk (P_t = {p_t if p_t is not None else 'N/A'}). "
                f"Graph relational evidence provides supporting multi-hop context. "
                f"The deterministic Risk Engine firmly confirms action '{action}' (Expected Loss: INR {expected_cost:.2f}) [RISK_ENGINE]."
            )
            t_interp = f"Instantaneous features indicate {t_assess} probability of fraudulent patterns (A_t = {a_t:.4f})."
            sb_interp = f"Persistent behavioral memory confirms {sb_assess} state across historical sequence."
            g_interp = f"Knowledge graph G_t = {graph_risk_g:.4f} reinforces entity and hardware relationship ties."
        elif t_assess in ("LOW", "MEDIUM") and sb_assess in ("HIGH", "CRITICAL"):
            status = "SLOW_BURN_ONLY"
            reasoning = (
                f"The Risk Council detects an asymmetric disagreement (Slow-Burn Only) for Transaction #{transaction_id}: "
                f"The transaction appears benign from isolated features alone (A_t = {a_t:.4f}, {t_assess}), but the "
                f"Slow-Burn Analyst flags persistent historical risk (P_t = {p_t:.4f}, {sb_assess}). "
                f"This represents an elevated historical risk association despite low instantaneous transaction features. "
                f"The deterministic Risk Engine combines both signals via F2 fusion to reach R_t = {final_risk_r:.4f}, enforcing '{action}' [RISK_ENGINE]."
            )
            t_interp = f"Transaction features alone appear relatively low-risk (A_t = {a_t:.4f})."
            sb_interp = f"Behavioral memory identifies elevated historical recidivism (P_t = {p_t:.4f}, {sb_assess})."
            g_interp = f"Relational context G_t = {graph_risk_g:.4f} exposes multi-entity device sharing or historical chargeback links."
        elif t_assess in ("HIGH", "CRITICAL") and sb_assess in ("LOW", "MEDIUM"):
            status = "ML_ONLY"
            reasoning = (
                f"The Risk Council detects divergence (ML Only) for Transaction #{transaction_id}: "
                f"Transaction features indicate severe acute anomaly (A_t = {a_t:.4f}, {t_assess}), whereas historical "
                f"behavioral memory has not accumulated persistent risk (P_t = {p_t if p_t is not None else 'N/A'}). "
                f"Deterministic Risk Engine maintains action '{action}' based on acute fraud probability [RISK_ENGINE]."
            )
            t_interp = f"Acute feature anomalies triggered high model risk (A_t = {a_t:.4f})."
            sb_interp = "Entity historical behavioral memory remains moderate or stable."
            g_interp = f"Graph context G_t = {graph_risk_g:.4f} provides contextual validation."
        else:
            status = "DISAGREEMENT"
            reasoning = (
                f"Independent analysts express divergent assessments for Transaction #{transaction_id} "
                f"(ML: {t_assess} vs Slow-Burn: {sb_assess}). Deterministic Risk Engine arbitrates via cost-minimising policy to '{action}' [RISK_ENGINE]."
            )
            t_interp = f"Transaction analyst reports {t_assess} risk."
            sb_interp = f"Slow-burn analyst reports {sb_assess} risk."
            g_interp = f"Graph context G_t = {graph_risk_g:.4f}."

        return {
            "council_status": status,
            "reasoning": reasoning,
            "transaction_analyst_interpretation": t_interp,
            "slow_burn_interpretation": sb_interp,
            "graph_interpretation": g_interp,
            "key_evidence": key_ev,
            "risk_engine_consistency": True,
            "llm_execution": {
                "provider": "deterministic_fallback",
                "model": "rule_based_fallback",
                "invoked": False,
                "is_fallback": True,
            },
        }

    def reconcile(
        self,
        transaction_id: int,
        transaction_analyst: Dict[str, Any],
        slow_burn_analyst: Dict[str, Any],
        council_status: str,
        graph_risk_g: float,
        final_risk_r: float,
        action: str,
        expected_cost: float,
        evidence_items: List[EvidenceItem],
    ) -> Tuple[str, List[str]]:
        """
        Backward-compatible method for existing callers, reusing council reasoning.
        """
        res = self.reason_council(
            transaction_id=transaction_id,
            transaction_analyst=transaction_analyst,
            slow_burn_analyst=slow_burn_analyst,
            graph_risk_g=graph_risk_g,
            final_risk_r=final_risk_r,
            action=action,
            expected_cost=expected_cost,
            evidence_items=evidence_items,
        )
        return res["reasoning"], res["key_evidence"]
